/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/collection': RouteRecordInfo<'/collection', '/collection', Record<never, never>, Record<never, never>>,
    '/game/': RouteRecordInfo<'/game/', '/game', Record<never, never>, Record<never, never>>,
    '/game/bmwk': RouteRecordInfo<'/game/bmwk', '/game/bmwk', Record<never, never>, Record<never, never>>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/notes/Energy_and_Human_Ambitions_on_a_Finite_Planet': RouteRecordInfo<'/notes/Energy_and_Human_Ambitions_on_a_Finite_Planet', '/notes/Energy_and_Human_Ambitions_on_a_Finite_Planet', Record<never, never>, Record<never, never>>,
    '/notes/everyDayWall': RouteRecordInfo<'/notes/everyDayWall', '/notes/everyDayWall', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/about-this-blog': RouteRecordInfo<'/posts/about-this-blog', '/posts/about-this-blog', Record<never, never>, Record<never, never>>,
    '/posts/fend-engine-eslint': RouteRecordInfo<'/posts/fend-engine-eslint', '/posts/fend-engine-eslint', Record<never, never>, Record<never, never>>,
    '/posts/fend-engine-git-ommit': RouteRecordInfo<'/posts/fend-engine-git-ommit', '/posts/fend-engine-git-ommit', Record<never, never>, Record<never, never>>,
    '/posts/fend-engine-husky': RouteRecordInfo<'/posts/fend-engine-husky', '/posts/fend-engine-husky', Record<never, never>, Record<never, never>>,
  }
}
